version: "2.2"

services:
  nginx:
    image: nginx
    depends_on:
      - php-fpm
    ports:
      - "80:80"
    volumes:
      - ./public:/src/public
      - ./docker/nginx-site.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    image: php:7.2-fpm
    depends_on:
      - composer
    volumes:
      - .:/src

  composer:
    image: composer
    volumes:
      - .:/app
    entrypoint: composer install --no-interaction --ignore-platform-reqs
